apiVersion: v1
kind: Service
metadata:
  name: python-redisapi-service
  namespace: my-namespace
spec:
  selector:
    app: python-redis
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080
    protocol: TCP
