apiVersion: v1
kind: Service
metadata:
  name: restplus-kubernetes-service
spec:
  selector:
    app: restplus-kubernetes
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    # nodePort: 30036
    protocol: TCP
