apiVersion: v1
kind: Service
metadata:
  name: restplus-kubernetes-service
spec:
  selector:
    app: restplus-kubernetes
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    protocol: TCP
